
/* Drop Tables */

DROP TABLE RECOMC CASCADE CONSTRAINTS;
DROP TABLE COM CASCADE CONSTRAINTS;
DROP TABLE RECOMB CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE MEM CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE BOARD
(
	BNUM number(10,0) NOT NULL UNIQUE,
	ID varchar2(30) NOT NULL,
	TITLE varchar2(30) NOT NULL,
	CONTENT varchar2(30) NOT NULL,
	REGDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (BNUM)
);


CREATE TABLE COM
(
	CNUM number(10,0) NOT NULL UNIQUE,
	BNUM number(10,0) NOT NULL,
	ID varchar2(30) NOT NULL,
	CONTENT varchar2(30) NOT NULL,
	REGDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (CNUM)
);


CREATE TABLE MEM
(
	ID varchar2(30) NOT NULL UNIQUE,
	PW varchar2(30) NOT NULL,
	NAME varchar2(30) NOT NULL,
	INFO varchar2(30) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE RECOMB
(
	RBNUM number(10,0) NOT NULL UNIQUE,
	BNUM number(10,0) NOT NULL,
	ID varchar2(30) NOT NULL,
	PRIMARY KEY (RBNUM)
);


CREATE TABLE RECOMC
(
	RCNUM number(10,0) NOT NULL UNIQUE,
	CNUM number(10,0) NOT NULL,
	ID varchar2(30) NOT NULL,
	PRIMARY KEY (RCNUM)
);



/* Create Foreign Keys */

ALTER TABLE COM
	ADD FOREIGN KEY (BNUM)
	REFERENCES BOARD (BNUM)
;


ALTER TABLE RECOMB
	ADD FOREIGN KEY (BNUM)
	REFERENCES BOARD (BNUM)
;


ALTER TABLE RECOMC
	ADD FOREIGN KEY (CNUM)
	REFERENCES COM (CNUM)
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (ID)
	REFERENCES MEM (ID)
;


ALTER TABLE COM
	ADD FOREIGN KEY (ID)
	REFERENCES MEM (ID)
;


ALTER TABLE RECOMB
	ADD FOREIGN KEY (ID)
	REFERENCES MEM (ID)
;


ALTER TABLE RECOMC
	ADD FOREIGN KEY (ID)
	REFERENCES MEM (ID)
;



