
/* Drop Triggers */

DROP TRIGGER TRI_PROPOSELIST_PROPONUM;



/* Drop Tables */

DROP TABLE COUNSELINFO CASCADE CONSTRAINTS;
DROP TABLE LECENROLL CASCADE CONSTRAINTS;
DROP TABLE TRAININGLIST CASCADE CONSTRAINTS;
DROP TABLE LECREPORT CASCADE CONSTRAINTS;
DROP TABLE LECINFO CASCADE CONSTRAINTS;
DROP TABLE PROPOSELIST CASCADE CONSTRAINTS;
DROP TABLE MEMINFO CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_PROPOSELIST_PROPONUM;




/* Create Sequences */

CREATE SEQUENCE SEQ_PROPOSELIST_PROPONUM INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE COUNSELINFO
(
	LECCODE varchar2(30) NOT NULL UNIQUE,
	COUNSELNUM number(10,0) NOT NULL UNIQUE,
	MEMID varchar2(30) NOT NULL,
	COUNSELIMG bfile,
	COUNSELSTATUS varchar2(30) NOT NULL,
	COUNSELDATE date DEFAULT SYSDATE NOT NULL,
	COUNSELCOUNT number(10,0) NOT NULL,
	COUNSELTYPE varchar2(30) NOT NULL,
	COUNSELQ varchar2(1000) NOT NULL,
	COUNSELA varchar2(1000) NOT NULL,
	PRIMARY KEY (LECCODE, COUNSELNUM),
	CONSTRAINT COUNSELINFONUM UNIQUE (LECCODE, COUNSELNUM)
);


CREATE TABLE LECENROLL
(
	MEMID varchar2(30) NOT NULL UNIQUE,
	LECCODE varchar2(30) NOT NULL UNIQUE,
	ENROLLDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (MEMID, LECCODE),
	CONSTRAINT ENROLL UNIQUE (MEMID, LECCODE)
);


CREATE TABLE LECINFO
(
	LECCODE varchar2(30) NOT NULL UNIQUE,
	MEMID varchar2(30) NOT NULL,
	LECNAME varchar2(30) NOT NULL,
	LECSTART date NOT NULL,
	LECEND date NOT NULL,
	LECWEEK varchar2(30) NOT NULL,
	LECTYPE varchar2(30) NOT NULL,
	LECRECRU number(10,0) NOT NULL,
	PRIMARY KEY (LECCODE)
);


CREATE TABLE LECREPORT
(
	LECCODE varchar2(30) NOT NULL UNIQUE,
	REPORTNUM number(10,0) NOT NULL UNIQUE,
	REPORTDATE date DEFAULT SYSDATE NOT NULL UNIQUE,
	ENROLL number(10,0) NOT NULL,
	ATTEND number(10,0) NOT NULL,
	ABSE number(10,0) NOT NULL,
	LATE number(10,0) NOT NULL,
	EARLY number(10,0) NOT NULL,
	LECCOM varchar2(100),
	APPRO varchar2(30) NOT NULL,
	DAYLECTHEORY number(10,0) NOT NULL,
	DAYLECPRAC number(10,0) NOT NULL,
	DAYLEC number(10,0) NOT NULL,
	SUMLECTHEORY number(10,0) NOT NULL,
	SUMLECPRAC number(10,0) NOT NULL,
	SUMLEC number(10,0) NOT NULL,
	ORDERCOM varchar2(1000),
	PRIMARY KEY (LECCODE, REPORTNUM),
	CONSTRAINT LECREPORTNUM UNIQUE (LECCODE, REPORTNUM)
);


CREATE TABLE MEMINFO
(
	MEMID varchar2(30) NOT NULL UNIQUE,
	MEMPW varchar2(30) NOT NULL,
	MEMNUM varchar2(30) NOT NULL,
	MEMNAME varchar2(30) NOT NULL,
	MEMADD varchar2(30) NOT NULL,
	MEMGRADE varchar2(30) NOT NULL,
	PRIMARY KEY (MEMID)
);


CREATE TABLE PROPOSELIST
(
	PROPONUM number(10,0) NOT NULL UNIQUE,
	MEMID varchar2(30) NOT NULL,
	PROPOTITLE varchar2(100) NOT NULL,
	PROPOCON varchar2(1000) NOT NULL,
	PROPODATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (PROPONUM)
);


CREATE TABLE TRAININGLIST
(
	LECCODE varchar2(30) NOT NULL UNIQUE,
	REPORTNUM number(10,0) NOT NULL UNIQUE,
	TRAININGPERIOD number(10,0) NOT NULL UNIQUE,
	MEMID varchar2(30) NOT NULL,
	TRAININGNAME varchar2(100) NOT NULL,
	TRAININGCONTENT varchar2(100),
	PRIMARY KEY (LECCODE, REPORTNUM, TRAININGPERIOD),
	CONSTRAINT TRAININGNUM UNIQUE (LECCODE, REPORTNUM, TRAININGPERIOD)
);



/* Create Foreign Keys */

ALTER TABLE COUNSELINFO
	ADD FOREIGN KEY (LECCODE)
	REFERENCES LECINFO (LECCODE)
;


ALTER TABLE LECENROLL
	ADD FOREIGN KEY (LECCODE)
	REFERENCES LECINFO (LECCODE)
;


ALTER TABLE LECREPORT
	ADD FOREIGN KEY (LECCODE)
	REFERENCES LECINFO (LECCODE)
;


ALTER TABLE TRAININGLIST
	ADD FOREIGN KEY (LECCODE, REPORTNUM)
	REFERENCES LECREPORT (LECCODE, REPORTNUM)
;


ALTER TABLE COUNSELINFO
	ADD FOREIGN KEY (MEMID)
	REFERENCES MEMINFO (MEMID)
;


ALTER TABLE LECENROLL
	ADD FOREIGN KEY (MEMID)
	REFERENCES MEMINFO (MEMID)
;


ALTER TABLE LECINFO
	ADD FOREIGN KEY (MEMID)
	REFERENCES MEMINFO (MEMID)
;


ALTER TABLE PROPOSELIST
	ADD FOREIGN KEY (MEMID)
	REFERENCES MEMINFO (MEMID)
;


ALTER TABLE TRAININGLIST
	ADD FOREIGN KEY (MEMID)
	REFERENCES MEMINFO (MEMID)
;



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_PROPOSELIST_PROPONUM BEFORE INSERT ON PROPOSELIST
FOR EACH ROW
BEGIN
	SELECT SEQ_PROPOSELIST_PROPONUM.nextval
	INTO :new.PROPONUM
	FROM dual;
END;

/




