
/* Drop Triggers */

DROP TRIGGER TRI_BUYLIST_BUYNUM;
DROP TRIGGER TRI_CONTRACTLOG_CONTRACTNUM;
DROP TRIGGER TRI_PAYMENTLIST_PAYMENTNUM;
DROP TRIGGER TRI_PAYMENTLOG_LOGNUM;
DROP TRIGGER TRI_PRODUCTINOUT_INOUTNUM;



/* Drop Tables */

DROP TABLE BUYLIST CASCADE CONSTRAINTS;
DROP TABLE CONTRACTLOG CASCADE CONSTRAINTS;
DROP TABLE PAYMENTLOG CASCADE CONSTRAINTS;
DROP TABLE PAYMENTLIST CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERLIST CASCADE CONSTRAINTS;
DROP TABLE DELIVERYMETHODLIST CASCADE CONSTRAINTS;
DROP TABLE DELIVERYCOMPANYS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTINOUT CASCADE CONSTRAINTS;
DROP TABLE PRODUCTLIST CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_BUYLIST_BUYNUM;
DROP SEQUENCE SEQ_CONTRACTLOG_CONTRACTNUM;
DROP SEQUENCE SEQ_PAYMENTLIST_PAYMENTNUM;
DROP SEQUENCE SEQ_PAYMENTLOG_LOGNUM;
DROP SEQUENCE SEQ_PRODUCTINOUT_INOUTNUM;




/* Create Sequences */

CREATE SEQUENCE SEQ_BUYLIST_BUYNUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CONTRACTLOG_CONTRACTNUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PAYMENTLIST_PAYMENTNUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PAYMENTLOG_LOGNUM INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PRODUCTINOUT_INOUTNUM INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE BUYLIST
(
	BUYNUM number(10,0) NOT NULL UNIQUE,
	PRODUCTCODE varchar2(30) NOT NULL UNIQUE,
	PAYMENTNUM number(10,0) NOT NULL UNIQUE,
	BUYVOL number(10,0) NOT NULL,
	PRIMARY KEY (BUYNUM),
	CONSTRAINT BUYLISTNUM UNIQUE (PRODUCTCODE, PAYMENTNUM)
);


CREATE TABLE CONTRACTLOG
(
	CONTRACTNUM number(10,0) NOT NULL UNIQUE,
	DELIVERYCOMPANYCODE varchar2(30) NOT NULL,
	CONTRACTSTATUS varchar2(30) NOT NULL,
	CONTRACTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (CONTRACTNUM)
);


CREATE TABLE CUSTOMERLIST
(
	CUSTOMERID varchar2(30) NOT NULL UNIQUE,
	CUSTOMERCATEGORY varchar2(30) NOT NULL,
	PRODUCTSALE number(3,3) NOT NULL,
	PRODUCTMILEAGE number(10,0) NOT NULL,
	PRIMARY KEY (CUSTOMERID)
);


CREATE TABLE DELIVERYCOMPANYS
(
	DELIVERYCOMPANYCODE varchar2(30) NOT NULL UNIQUE,
	DELIVERYCOMPANYNAME varchar2(30) NOT NULL,
	PRIMARY KEY (DELIVERYCOMPANYCODE)
);


CREATE TABLE DELIVERYMETHODLIST
(
	DELIVERYMETHODCODE number(10,0) NOT NULL UNIQUE,
	DELIVERYCOMPANYCODE varchar2(30) NOT NULL,
	DELIVERYMETHOD varchar2(30) NOT NULL,
	DELIVERYSCHEDULE varchar2(30) NOT NULL,
	PRIMARY KEY (DELIVERYMETHODCODE)
);


CREATE TABLE PAYMENTLIST
(
	PAYMENTNUM number(10,0) NOT NULL UNIQUE,
	CUSTOMERID varchar2(30) NOT NULL,
	RESULTPAY number(10,0) NOT NULL,
	RESULTMILEAGE number(10,0) NOT NULL,
	DELIVERYSTATUS varchar2(30) NOT NULL,
	ETA date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (PAYMENTNUM)
);


CREATE TABLE PAYMENTLOG
(
	LOGNUM number(10,0) NOT NULL UNIQUE,
	PAYMENTNUM number(10,0) NOT NULL,
	DELIVERYSTATUS varchar2(30) NOT NULL,
	LOGDATE date DEFAULT SYSDATE NOT NULL,
	IFSMS varchar2(30) NOT NULL,
	SMS varchar2(1000),
	DELIVERYCOMPANYCODE varchar2(30) NOT NULL UNIQUE,
	PRIMARY KEY (LOGNUM)
);


CREATE TABLE PRODUCTINOUT
(
	INOUTNUM number(10,0) NOT NULL UNIQUE,
	PRODUCTCODE varchar2(30) NOT NULL UNIQUE,
	INOUTSTOCK number(10,0) NOT NULL,
	INOUTCATEGORY varchar2(30) NOT NULL,
	INOUTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (INOUTNUM)
);


CREATE TABLE PRODUCTLIST
(
	PRODUCTCODE varchar2(30) NOT NULL UNIQUE,
	PRODUCTCATEGORY varchar2(30) NOT NULL,
	PRODUCTNAME varchar2(30) NOT NULL,
	PRODUCTSTOCK number(10,0) NOT NULL,
	PRIMARY KEY (PRODUCTCODE)
);



/* Create Foreign Keys */

ALTER TABLE PAYMENTLIST
	ADD FOREIGN KEY (CUSTOMERID)
	REFERENCES CUSTOMERLIST (CUSTOMERID)
;


ALTER TABLE CONTRACTLOG
	ADD FOREIGN KEY (DELIVERYCOMPANYCODE)
	REFERENCES DELIVERYCOMPANYS (DELIVERYCOMPANYCODE)
;


ALTER TABLE DELIVERYMETHODLIST
	ADD FOREIGN KEY (DELIVERYCOMPANYCODE)
	REFERENCES DELIVERYCOMPANYS (DELIVERYCOMPANYCODE)
;


ALTER TABLE PAYMENTLOG
	ADD FOREIGN KEY (DELIVERYCOMPANYCODE)
	REFERENCES DELIVERYCOMPANYS (DELIVERYCOMPANYCODE)
;


ALTER TABLE BUYLIST
	ADD FOREIGN KEY (PAYMENTNUM)
	REFERENCES PAYMENTLIST (PAYMENTNUM)
;


ALTER TABLE PAYMENTLOG
	ADD FOREIGN KEY (PAYMENTNUM)
	REFERENCES PAYMENTLIST (PAYMENTNUM)
;


ALTER TABLE BUYLIST
	ADD FOREIGN KEY (PRODUCTCODE)
	REFERENCES PRODUCTLIST (PRODUCTCODE)
;


ALTER TABLE PRODUCTINOUT
	ADD FOREIGN KEY (PRODUCTCODE)
	REFERENCES PRODUCTLIST (PRODUCTCODE)
;



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_BUYLIST_BUYNUM BEFORE INSERT ON BUYLIST
FOR EACH ROW
BEGIN
	SELECT SEQ_BUYLIST_BUYNUM.nextval
	INTO :new.BUYNUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_CONTRACTLOG_CONTRACTNUM BEFORE INSERT ON CONTRACTLOG
FOR EACH ROW
BEGIN
	SELECT SEQ_CONTRACTLOG_CONTRACTNUM.nextval
	INTO :new.CONTRACTNUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_PAYMENTLIST_PAYMENTNUM BEFORE INSERT ON PAYMENTLIST
FOR EACH ROW
BEGIN
	SELECT SEQ_PAYMENTLIST_PAYMENTNUM.nextval
	INTO :new.PAYMENTNUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_PAYMENTLOG_LOGNUM BEFORE INSERT ON PAYMENTLOG
FOR EACH ROW
BEGIN
	SELECT SEQ_PAYMENTLOG_LOGNUM.nextval
	INTO :new.LOGNUM
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_PRODUCTINOUT_INOUTNUM BEFORE INSERT ON PRODUCTINOUT
FOR EACH ROW
BEGIN
	SELECT SEQ_PRODUCTINOUT_INOUTNUM.nextval
	INTO :new.INOUTNUM
	FROM dual;
END;

/




